[lintrunner]
mode = 'whole_repo'
verbose = true

[[linter]]
name = "flake8"
code = 'FLAKE8'
include_patterns = ['**/*.py']
exclude_patterns = [
    '.git/**',
    '**/*.pyi',
    'tools/**',
]
command = [
    'python',
    'tools/linter/adapters/flake8_linter.py',
    '--',
    '--max-line-length=120',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    'tools/linter/adapters/pip_init.py',
    '--dry-run={{DRYRUN}}',
    'flake8==7.3.0',
    'flake8-bugbear==24.12.12',
    'flake8-comprehensions==3.16.0',
    'flake8-executable==2.1.3',
    'flake8-logging-format==2024.24.12',
    'flake8-pyi==25.5.0',
    'flake8-simplify==0.22.0',
    'mccabe==0.7.0',
    'pycodestyle==2.14.0',
    'pyflakes==3.4.0',
    'torchfix==0.4.0 ; python_version >= "3.9" and python_version < "3.13"',
]
is_formatter = true

[[linter]]
code = 'PYFMT'
include_patterns = [
    '**/*.py',
    '**/*.pyi',
]
exclude_patterns = [
    '.git/**',
    'tools/**',
]
command = [
    'python',
    'tools/linter/adapters/pyfmt_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    'tools/linter/adapters/pip_init.py',
    '--dry-run={{DRYRUN}}',
    '--no-black-binary',
    'black==23.12.1',
    'usort==1.0.8.post1',
    'isort==6.0.1',
    'ruff==0.12.2',  # sync with RUFF
]
is_formatter = true

[[linter]]
code = 'RUFF'
include_patterns = [
    '**/*.py',
    '**/*.pyi',
    '**/*.ipynb',
    'pyproject.toml',
]
exclude_patterns = [
    '.git/**',
    'tools/**',
]
command = [
    'python',
    'tools/linter/adapters/ruff_linter.py',
    '--config=pyproject.toml',
    '--show-disable',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    'tools/linter/adapters/pip_init.py',
    '--dry-run={{DRYRUN}}',
    'ruff==0.12.2',  # sync with PYFMT
]
is_formatter = true
